export const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "";
export const FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "";
export const FIREBASE_PROJECT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "";
export const FIREBASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || "";
export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "";
export const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "";
export const FIREBASE_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || "";
export const FIREBASE_DATABASE_URL =
  process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL || "";
export const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL || "";
export const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY || "";


// NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyCB8GKw_woyGUfm0RHvdDIUtevZscQgorw"
// NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="immersive-f4944.firebaseapp.com"
// NEXT_PUBLIC_FIREBASE_PROJECT_ID="immersive-f4944"
// NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="immersive-f4944.firebasestorage.app"
// NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="367393525682"
// NEXT_PUBLIC_FIREBASE_APP_ID="1:367393525682:web:26265bf904d4c9d754deab"
// NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-RNFBFM7S9V"
// NEXT_PUBLIC_FIREBASE_DATABASE_URL="https://humeo-2f9dd-default-rtdb.firebaseio.com"

// FIREBASE_CLIENT_EMAIL="firebase-adminsdk-fbsvc@immersive-f4944.iam.gserviceaccount.com"
// FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC99WGx09A7eGX+\neymRyWVqTFrzCulRhQ/+Ae1CDYV1El0u9UF1YarReGbsn8A7l0t/JM70I+/mnHmv\nltGmn6CnB42QIdwuslIdrptZEpcJDan/DgYMIZr1zlkvh4hu6LSEHhStXJ67heQX\n7OBTDuyUqxXAnI90k8pcXBRIF6B5OY8v31EPLMDiYr3TRKh8KkW/Z316XlANLBzR\nUKQNUcukCfvpt+IgbX+RkApVMB4RcEDsGy4SJeDIz0xpZe38zu/NrIw6R/BYRRce\nAZ1p//0bhWqb5FH7XLN+Eg+BQA82kdApouHSTyOBT2yVySyfzoKuopojwa9ZEB7m\nmfJvI7DvAgMBAAECggEAO/co6nqbmxJ0XCPkKQYDMk29TkkNA3N2a3CPRdE/5oew\nC+FXUydMRcj08NCzXfxyVEY54J8xncKatV/ueeOdUu0S9sOBnuoi+wTCPJmePTjn\nh8EVDqJTKTKFO/hUjPJ//c8DJwD8iOUI7raT0BR/gaUKfl3N+XaoJITa0DFJMsr5\nkfbIRzayfqiUp2x0+DSz+kYPAjbR6p+unlFl4g5O4Yux4x3L0lPSGG1hwNRruJRY\naK853HnqA3CSww8Hy7nwuMKRFRj/ul6taW5MbUZlcn6RbuY0bQ+OdAXP9R3L6QpN\niHICQwnDXV/EfqouHmeeWY6TKCUmLiO11pBtCBi9XQKBgQDwsUUBEOq7WZGDRAfu\nQYSPC3eFtAndFx6i67NFxtm17mx1bPH5Hk9/ptktnxWrx/kigjZpKt/ExFPCso27\nacfGyycBmRrCwcyWyutWRQaJb4Jjc5s0CSj48Vk+sLWJ+e+WhsSf5ebNYIipZ+Ts\nyot78igugfNaMxnl5hTNePsvLQKBgQDKChv+1P88hsGPMqKEewI4ONo95RsvyIPX\n1AGblTvLC9+r6KXGjrWG2KkvxopAVUHGR3+UezoGvf/CEfHVB5te5wXjCKWlxakE\nLkpOZqCCw23yVRDEkLN/HC7ezFMYzJJnb4JguMn8vIOlt7FYZPob9jKhQI4DvGs+\nfIxAh9WSCwKBgADs7ZL/eaeWxJR4on8sCVJzfNYqxw7uk9OUjG/sP9IPRKN+8789\nepjHD3a5cd/jOPYFAiiNXaboClppTVo3IemFxnSfHhc5n4vE4/rE8S1+HEY9n48n\nqdyrMOiozUnmiCFQC1mCDM0lXeEo4Rx3+ulTGQx0u3bRU3wq0lGn8W9RAoGBAIOi\nQIkwpzb9KWEuAVrFdjXBPNf0zFi+kL/u3jlK6tEo5Erx4ghS9Ixt3xVEitDNe3Q/\nIy1PeAfqhJch7+j28tDLPjeka6Bs/ui9bCZWkR+BSsIHkEwxZvFbIGKCx2Ux6/U+\nXri7zMZA4Jj47LAF4jqTlnsfPyfJ/CmTJiHpHknvAoGBAKDvuQRLoRAYm1AzO8/S\nLx02c5rgLWNAzqeDQ3652YoD1AUDn41Y3eqza2oPz3OVsEfOuZKAb/EX8wkUILrj\nOT8iipeI3HKar/90Ujn+ZhYOuw78wN8sTfWHdA2ROH8bZm6wVvEg3lV4DlFGTIhV\ntLzZCSNUPNQDaIQsSgJiNLFu\n-----END PRIVATE KEY-----\n"