export const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "";
export const FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "";
export const FIREBASE_PROJECT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "";
export const FIREBASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || "";
export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "";
export const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "";
export const FIREBASE_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || "";
export const FIREBASE_DATABASE_URL =
  process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL || "";
export const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL || "";
export const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY || "";

// NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyBpSLcqbxDf1fPx2M-n30DIUVq1hY0iMqc"
// NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="humeo-2f9dd.firebaseapp.com"
// NEXT_PUBLIC_FIREBASE_PROJECT_ID="humeo-2f9dd"
// NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="humeo-2f9dd.firebasestorage.app"
// NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="677019542369"
// NEXT_PUBLIC_FIREBASE_APP_ID="1:677019542369:web:6c47d5de7a68c506941b20"
// NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-Y3JJT4FH9T"
// NEXT_PUBLIC_FIREBASE_DATABASE_URL="https://humeo-2f9dd-default-rtdb.firebaseio.com"

// FIREBASE_CLIENT_EMAIL="firebase-adminsdk-fbsvc@humeo-2f9dd.iam.gserviceaccount.com"
// FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDKv4VPZdahRW5n\n1WpeOQ67Os7BsRiG6MNcoSNUZf+IC13Ouhl6dPXzlxNpJ7DRov8bRws45Cfho66k\n0XvziObbRnMnT5lrVOgxvou+zyX/p5VOL+RYAE77wscPaqVCdzCL57/DeKIHKyZV\nH+Nn3SzAI7znusk5Crgmy8Zn3U6y3sIClOPzUm4cBmRR+vQrqN9L7G9LjrhBA+el\n7XYx3itmaNB0w8YiPaDuS0mS4qyXILOKsQoEtIpT35VXlm8RXvh1rqE52ODSu9hQ\nPWfnNtgZYAxJZp0vNk8K2y+CvosQI8pUx6ufCrmTTeutqpvZIJvfbv6CuO6D5dYw\nlmEF1gnbAgMBAAECggEAVU5A8ne4VzGl8vVGJG/gZWGodbGkTrsn29UGzu99lQmn\nRiBiMPZ+N6gUqDVlfccVjC4XqC/DIfqjNEDZ5M1wyMj7EYq51AGtEqUIGlgBNnCV\n7whSjL5QfThmVfO6pd0NZYg0VLPwhJCgt8dLgLt8JTnENUIPgTsj4Vry12ezwakc\nuwRDSPNq28aLqc29D5ui1CP8mRllV/9WBS8YGWIiiIYdN9gWKpgNOToC0xyS6TPJ\n+9EDU+3WgMgRmfAL22YdtXm2ktYjUCLctJlnNbn3lueqTfdMO+kwmftoj1ef33Gv\nW0jf+FpVTr4f3Jj6oysAwzW2UDAu7ng8hsB82LxAjQKBgQD5aI+nm3zXWwOcJY2A\nSqLYbtM46ap54Vyyr75/6C3qp1HARlTPx0VKesqZt52j2ST5BOE9gOC8kQxloj7V\nZJopsRV2kF+0OiuOG5w+rFyIAce9QK3aKgs0vxoR9TQ1X6YGpTZkSQGK229uajle\nJMbcsUVfTV5Bg2rf3sxnYZuA3wKBgQDQG0RSaedVDxqGszCCbajTb/Z8//gikIk7\nx9BRprwO53W+Q9Ig7gjxl69F9UeRhkS+vJPklrf4nCW7IA9I8mc5fZrQaGCE8atU\nsAC3wEepKwmteBYWNP2bTc+HQxv7231CoUqR3r0zhG/LwdEa1SiheXEPxcCCnVhI\nNWYHKoiqhQKBgD9myT3+VNoaFOzYzwPR9Vu3sJJDNEcPdxUlf/Pb/fAs4KdUObMo\nIQEx/dbdyoEgbjmvd+K+pGLLLK+ZcwekL1xx29bsFKgoMXJKqol0H4GjkjcV/hv7\nnCWofuQZxU/cJMSDszQDKxU1ezpCXpsEFll75vq3HELjOYP3i1ashW9ZAoGAe6QH\nlpNXHsEneGoT4xn12RFHOAL4UMjg0ASqLyjJyG0aFl3DBU+HPsppFz5gNAS66Tuu\n/nvRd8KF5ERq8GMckxqeFT4+Qh43NcyP0JxLtyVbzZVwQedf2ZqENw/XG27PX/vm\nCv50GJyRs1RGwRNt3WoCk2VhN/j1z4jyQkWyBuUCgYEAuFWW+uNZUCU1laZN1jfI\ny8WYYykZ3SLOAwetQKNtq3+b/Ys691eyiDsaME/pyBoisfZDmSsH/nziWwwUy9I1\nVS8MzkKEQ5IRt2VPUOt4CkzDF2Ig9QMPUKsvz1TPawbaLpnNEHgk8vt6yQzd2pmC\nP0fG/zgb081iCp3LFnk9TOI=\n-----END PRIVATE KEY-----\n"
//  db.collection("users").doc(userid).get();
