import { ProjectsRoot } from "./types";

export const demoData: ProjectsRoot = {
  projects: {
    project_001: {
      projectId: "project_001",
      name: "Skyline Residency",
      location: "Hyderabad",
      description: "Luxury apartments with modern amenities",
      blocks: {
        block_A: {
          blockId: "block_A",
          name: "Block A",
          modelPath: "/BlockA.glb",
          floors: {
            floor_1: {
              floorId: "floor_1",
              flats: {
                flat_101: {
                  flatId: "flat_101",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 700,
                  carpetSqft: 490,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3500000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_102: {
                  flatId: "flat_102",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1100,
                  carpetSqft: 770,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 5500000,
                  priceBand: "50–60L",
                  status: "sold",
                },
              },
            },
            floor_2: {
              floorId: "floor_2",
              flats: {
                flat_201: {
                  flatId: "flat_201",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 720,
                  carpetSqft: 500,
                  facing: "West",
                  view: "Road",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "None",
                  priceBase: 3600000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_202: {
                  flatId: "flat_202",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1250,
                  carpetSqft: 880,
                  facing: "East",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6200000,
                  priceBand: "60–70L",
                  status: "reserved",
                },
              },
            },
            floor_3: {
              floorId: "floor_3",
              flats: {
                flat_301: {
                  flatId: "flat_301",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1180,
                  carpetSqft: 820,
                  facing: "South",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 5900000,
                  priceBand: "50–60L",
                  status: "available",
                },
                flat_302: {
                  flatId: "flat_302",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1500,
                  carpetSqft: 1050,
                  facing: "North",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7500000,
                  priceBand: "70–80L",
                  status: "sold",
                },
              },
            },
            floor_4: {
              floorId: "floor_4",
              flats: {
                flat_401: {
                  flatId: "flat_401",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1520,
                  carpetSqft: 1060,
                  facing: "North",
                  view: "Park",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7600000,
                  priceBand: "70–80L",
                  status: "reserved",
                },
                flat_402: {
                  flatId: "flat_402",
                  bhk: "4BHK",
                  superBuiltUpSqft: 2000,
                  carpetSqft: 1400,
                  facing: "East",
                  view: "City",
                  balconyCount: 3,
                  bathCount: 4,
                  parking: "Covered",
                  priceBase: 10000000,
                  priceBand: "1Cr+",
                  status: "available",
                },
              },
            },
            floor_5: {
              floorId: "floor_5",
              flats: {
                flat_501: {
                  flatId: "flat_501",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 730,
                  carpetSqft: 510,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3650000,
                  priceBand: "30–40L",
                  status: "sold",
                },
                flat_502: {
                  flatId: "flat_502",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1260,
                  carpetSqft: 890,
                  facing: "West",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6400000,
                  priceBand: "60–70L",
                  status: "available",
                },
              },
            },
            floor_6: {
              floorId: "floor_6",
              flats: {
                flat_601: {
                  flatId: "flat_601",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1200,
                  carpetSqft: 840,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6000000,
                  priceBand: "50–60L",
                  status: "available",
                },
                flat_602: {
                  flatId: "flat_602",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1520,
                  carpetSqft: 1065,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7600000,
                  priceBand: "70–80L",
                  status: "reserved",
                },
              },
            },
            floor_7: {
              floorId: "floor_7",
              flats: {
                flat_701: {
                  flatId: "flat_701",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1540,
                  carpetSqft: 1080,
                  facing: "South",
                  view: "Park",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7700000,
                  priceBand: "70–80L",
                  status: "available",
                },
                flat_702: {
                  flatId: "flat_702",
                  bhk: "4BHK",
                  superBuiltUpSqft: 2020,
                  carpetSqft: 1420,
                  facing: "North",
                  view: "City",
                  balconyCount: 3,
                  bathCount: 4,
                  parking: "Covered",
                  priceBase: 10200000,
                  priceBand: "1Cr+",
                  status: "sold",
                },
              },
            },
            floor_8: {
              floorId: "floor_8",
              flats: {
                flat_801: {
                  flatId: "flat_801",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 740,
                  carpetSqft: 520,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3700000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_802: {
                  flatId: "flat_802",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1270,
                  carpetSqft: 900,
                  facing: "West",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6500000,
                  priceBand: "60–70L",
                  status: "reserved",
                },
              },
            },
            floor_9: {
              floorId: "floor_9",
              flats: {
                flat_901: {
                  flatId: "flat_901",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1210,
                  carpetSqft: 850,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6050000,
                  priceBand: "60–70L",
                  status: "sold",
                },
                flat_902: {
                  flatId: "flat_902",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1550,
                  carpetSqft: 1090,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7800000,
                  priceBand: "70–80L",
                  status: "available",
                },
              },
            },
            floor_10: {
              floorId: "floor_10",
              flats: {
                flat_1001: {
                  flatId: "flat_1001",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1560,
                  carpetSqft: 1100,
                  facing: "South",
                  view: "Park",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7900000,
                  priceBand: "70–80L",
                  status: "available",
                },
                flat_1002: {
                  flatId: "flat_1002",
                  bhk: "4BHK",
                  superBuiltUpSqft: 2050,
                  carpetSqft: 1440,
                  facing: "North",
                  view: "City",
                  balconyCount: 3,
                  bathCount: 4,
                  parking: "Covered",
                  priceBase: 10300000,
                  priceBand: "1Cr+",
                  status: "reserved",
                },
              },
            },
            floor_11: {
              floorId: "floor_11",
              flats: {
                flat_1101: {
                  flatId: "flat_1101",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 760,
                  carpetSqft: 530,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3800000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_1102: {
                  flatId: "flat_1102",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1280,
                  carpetSqft: 910,
                  facing: "West",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6600000,
                  priceBand: "60–70L",
                  status: "sold",
                },
              },
            },
            floor_12: {
              floorId: "floor_12",
              flats: {
                flat_1201: {
                  flatId: "flat_1201",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1220,
                  carpetSqft: 860,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6100000,
                  priceBand: "60–70L",
                  status: "available",
                },
                flat_1202: {
                  flatId: "flat_1202",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1570,
                  carpetSqft: 1100,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7950000,
                  priceBand: "70–80L",
                  status: "reserved",
                },
              },
            },
            floor_13: {
              floorId: "floor_13",
              flats: {
                flat_1301: {
                  flatId: "flat_1301",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1580,
                  carpetSqft: 1115,
                  facing: "South",
                  view: "Park",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 8050000,
                  priceBand: "80–90L",
                  status: "available",
                },
                flat_1302: {
                  flatId: "flat_1302",
                  bhk: "4BHK",
                  superBuiltUpSqft: 2060,
                  carpetSqft: 1450,
                  facing: "North",
                  view: "City",
                  balconyCount: 3,
                  bathCount: 4,
                  parking: "Covered",
                  priceBase: 10400000,
                  priceBand: "1Cr+",
                  status: "sold",
                },
              },
            },
            floor_14: {
              floorId: "floor_14",
              flats: {
                flat_1401: {
                  flatId: "flat_1401",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 770,
                  carpetSqft: 540,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3850000,
                  priceBand: "30–40L",
                  status: "reserved",
                },
                flat_1402: {
                  flatId: "flat_1402",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1290,
                  carpetSqft: 920,
                  facing: "West",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6700000,
                  priceBand: "60–70L",
                  status: "available",
                },
              },
            },
            floor_15: {
              floorId: "floor_15",
              flats: {
                flat_1501: {
                  flatId: "flat_1501",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1230,
                  carpetSqft: 870,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6150000,
                  priceBand: "60–70L",
                  status: "available",
                },
                flat_1502: {
                  flatId: "flat_1502",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1590,
                  carpetSqft: 1125,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 8150000,
                  priceBand: "80–90L",
                  status: "reserved",
                },
              },
            },
          }
        },
        block_B: {
          blockId: "block_B",
          name: "Block B",
          modelPath: "/BlockA.glb",
          floors: {
            floor_1: {
              floorId: "floor_1",
              flats: {
                flat_101: {
                  flatId: "flat_101",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 700,
                  carpetSqft: 490,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3500000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_102: {
                  flatId: "flat_102",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1100,
                  carpetSqft: 770,
                  facing: "West",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 5500000,
                  priceBand: "50–60L",
                  status: "sold",
                },
              },
            },
            floor_2: {
              floorId: "floor_2",
              flats: {
                flat_201: {
                  flatId: "flat_201",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 720,
                  carpetSqft: 500,
                  facing: "West",
                  view: "Road",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "None",
                  priceBase: 3600000,
                  priceBand: "30–40L",
                  status: "available",
                },
                flat_202: {
                  flatId: "flat_202",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1250,
                  carpetSqft: 880,
                  facing: "East",
                  view: "City",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6200000,
                  priceBand: "60–70L",
                  status: "reserved",
                },
              },
            },
            floor_3: {
              floorId: "floor_3",
              flats: {
                flat_301: {
                  flatId: "flat_301",
                  bhk: "2BHK",
                  superBuiltUpSqft: 1180,
                  carpetSqft: 820,
                  facing: "South",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 5900000,
                  priceBand: "50–60L",
                  status: "available",
                },
                flat_302: {
                  flatId: "flat_302",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1500,
                  carpetSqft: 1050,
                  facing: "North",
                  view: "Garden",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7500000,
                  priceBand: "70–80L",
                  status: "sold",
                },
              },
            },
            floor_4: {
              floorId: "floor_4",
              flats: {
                flat_401: {
                  flatId: "flat_401",
                  bhk: "3BHK",
                  superBuiltUpSqft: 1520,
                  carpetSqft: 1060,
                  facing: "North",
                  view: "Park",
                  balconyCount: 2,
                  bathCount: 3,
                  parking: "Covered",
                  priceBase: 7600000,
                  priceBand: "70–80L",
                  status: "reserved",
                },
                flat_402: {
                  flatId: "flat_402",
                  bhk: "4BHK",
                  superBuiltUpSqft: 2000,
                  carpetSqft: 1400,
                  facing: "East",
                  view: "City",
                  balconyCount: 3,
                  bathCount: 4,
                  parking: "Covered",
                  priceBase: 10000000,
                  priceBand: "1Cr+",
                  status: "available",
                },
              },
            },
            floor_5: {
              floorId: "floor_5",
              flats: {
                flat_501: {
                  flatId: "flat_501",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 730,
                  carpetSqft: 510,
                  facing: "East",
                  view: "Garden",
                  balconyCount: 1,
                  bathCount: 1,
                  parking: "Open",
                  priceBase: 3650000,
                  priceBand: "30–40L",
                  status: "sold",
                },
                flat_502: {
                  flatId: "flat_502",
                  bhk: "2.5BHK",
                  superBuiltUpSqft: 1260,
                  carpetSqft: 890,
                  facing: "West",
                  view: "Pool",
                  balconyCount: 2,
                  bathCount: 2,
                  parking: "Covered",
                  priceBase: 6400000,
                  priceBand: "60–70L",
                  status: "available",
                },
              },
            },
          },
        },
      },
    },
  },
};
